export function loginPage(nonce: string): string {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Connect to Meuhedet · Local sign-in</title>
<style nonce="${nonce}">
*{box-sizing:border-box}body{margin:0;background:#f3f5ed;color:#183e35;font-family:Verdana,sans-serif;line-height:1.6}main{max-width:540px;margin:clamp(24px,8vh,90px) auto;padding:32px}header{border-top:3px solid #285b49;padding-top:20px}small{font-size:12px;letter-spacing:.08em;text-transform:uppercase}h1{font-family:Georgia,serif;font-weight:400;font-size:clamp(32px,6vw,44px);line-height:1.12;margin:24px 0 16px}p{font-size:14px}form{margin:32px 0}label{display:block;font-size:14px;margin:22px 0 8px}input{width:100%;padding:12px;border:1px solid #73877a;border-radius:3px;background:#fbfcf7;color:#183e35;font:inherit}button{min-height:46px;padding:12px 18px;border:0;border-radius:3px;background:#285b49;color:#fbfcf7;font:inherit;font-size:14px;cursor:pointer}button:disabled{opacity:.6;cursor:wait}input:focus-visible,button:focus-visible{outline:3px solid #b98031;outline-offset:3px}.actions{display:flex;gap:16px;align-items:center;margin-top:26px}.secondary{background:transparent;color:#285b49;text-decoration:underline}footer{border-top:1px solid #b7c3b3;padding-top:20px;font-size:12px}#message{min-height:24px;font-size:14px}a{color:inherit}
</style></head><body><main><header><small>Meuhedet Health · Local connection</small>
<h1 id="title">Connect your account</h1><p id="intro">Enter your details to receive a sign-in code from Meuhedet.</p></header>
<form id="form"><div id="fields"></div><div class="actions"><button id="submit" type="submit">Send SMS code</button><button id="cancel" class="secondary" type="button">Cancel</button></div></form>
<p id="message" role="status" aria-live="polite"></p>
<footer>This is an unofficial local client, not Meuhedet’s website. Your details are sent to Meuhedet for sign-in. The session is stored privately on this computer so your agent can read your records. This page expires after ten minutes.</footer>
</main><script nonce="${nonce}">
const token=location.hash.slice(1);history.replaceState(null,'',location.pathname);
const form=document.getElementById('form'),fields=document.getElementById('fields'),submit=document.getElementById('submit'),cancel=document.getElementById('cancel'),message=document.getElementById('message');
let step='credentials';
async function request(path,data){const response=await fetch(path,{method:data?'POST':'GET',headers:{Authorization:'Bearer '+token,...(data?{'Content-Type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{})});if(response.status===403)throw Error('This sign-in link is invalid. Ask your agent to open a new one.');return response.json()}
function render(state){step=state;if(state==='credentials'){fields.innerHTML='<label for="username">ID number</label><input id="username" name="username" inputmode="numeric" pattern="[0-9]{5,9}" maxlength="9" autocomplete="off" required><label for="phone">Mobile number</label><input id="phone" name="mobilePhoneNumber" type="tel" pattern="05[0-9]{8}" maxlength="10" autocomplete="off" required>';submit.textContent='Send SMS code'}else if(state==='otp'){document.getElementById('title').textContent='Check your phone';document.getElementById('intro').textContent='Enter the SMS code sent by Meuhedet.';fields.innerHTML='<label for="code">SMS code</label><input id="code" name="code" inputmode="numeric" pattern="[0-9]{4,8}" maxlength="8" autocomplete="one-time-code" required>';submit.textContent='Connect account';document.getElementById('code').focus()}else{form.hidden=true;fields.replaceChildren();const done=state==='complete';document.getElementById('title').textContent=done?'Your account is connected':'Sign-in ended';document.getElementById('intro').textContent=done?'Your agent can now retrieve your records. You can close this page.':'Ask your agent to start a new sign-in when you are ready.'}}
form.addEventListener('submit',async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(form));form.reset();submit.disabled=true;cancel.disabled=true;message.textContent=step==='credentials'?'Requesting your SMS code…':'Connecting your account…';try{const result=await request(step==='credentials'?'/credentials':'/otp',data);message.textContent=result.message||'';if(result.state!==step)render(result.state)}catch(error){message.textContent=error.message||'The local sign-in connection ended. Ask your agent to start a new one.';form.hidden=true;fields.replaceChildren()}finally{submit.disabled=false;cancel.disabled=false}});
cancel.addEventListener('click',async()=>{try{await request('/cancel',{});render('cancelled')}catch{render('cancelled')}});
request('/state').then(result=>render(result.state)).catch(error=>{form.hidden=true;message.textContent=error.message});
</script></body></html>`;
}
