export const signInComponent = `
<style>
:root{color-scheme:light dark}*{box-sizing:border-box}body{margin:0;font-family:system-ui,sans-serif;color:light-dark(#23382e,#e5ece8);background:transparent}.sign-in{padding:20px;max-width:520px}h2{font-size:22px;margin:0 0 12px;font-weight:500}p{font-size:14px;line-height:1.5}label{display:block;margin:16px 0 6px;font-size:14px}input{font:inherit;width:100%;min-height:44px;padding:10px;border:1px solid light-dark(#86968c,#788a80);border-radius:6px;background:light-dark(#fafcf9,#20332a);color:inherit}button{font:inherit;min-height:44px;padding:10px 16px;border:1px solid light-dark(#86968c,#788a80);border-radius:6px;background:light-dark(#e5eee6,#30483a);color:inherit}button:disabled{opacity:.6}.actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:20px}.privacy{font-size:12px;color:light-dark(#53675b,#b3c7b9)}#message{min-height:22px}
</style>
<section class="sign-in" aria-labelledby="title">
  <h2 id="title">Connect your Meuhedet account</h2>
  <p id="intro">Enter your details to receive an SMS sign-in code.</p>
  <form id="form" hidden>
    <div id="fields"></div>
    <div class="actions"><button id="submit" type="submit">Send SMS code</button><button id="cancel" type="button">Cancel</button><button id="forget" type="button" hidden>Use different details</button></div>
  </form>
  <p id="message" role="status" aria-live="polite">Connecting to the local client…</p>
  <p class="privacy">Unofficial Meuhedet client. This form sends your details to Meuhedet through the local client. Credentials are not included in model-facing results. After successful sign-in, your ID, phone number and session are saved in private files on this computer. Your SMS code is never saved. Sign-in expires after ten minutes.</p>
</section>
<script>
const form=document.getElementById('form'),fields=document.getElementById('fields'),submit=document.getElementById('submit'),cancel=document.getElementById('cancel'),message=document.getElementById('message'),forget=document.getElementById('forget');
const pending=new Map();let nextId=1,flowId,step,hasSavedDetails=false;
function request(method,params){const id=nextId++;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{pending.delete(id);reject(Error('The sign-in connection timed out. Ask your agent to check the local client.'))},45000);pending.set(id,{resolve,reject,timer});window.parent.postMessage({jsonrpc:'2.0',id,method,params},'*')})}
function render(result){const data=result?.structuredContent;if(!data)return;flowId=result._meta?.flowId||flowId;step=data.state;hasSavedDetails=!!result._meta?.hasSavedDetails;forget.hidden=step!=='credentials'||!hasSavedDetails;message.textContent=data.error?'Sign-in could not continue. Ask your agent to check the sign-in status.':'';form.hidden=!['credentials','otp'].includes(step);if(step==='credentials'){document.getElementById('intro').textContent=hasSavedDetails?'Send a new SMS code using your saved ID and phone number.':'Enter your details to receive an SMS sign-in code.';fields.innerHTML=hasSavedDetails?'':'<label for="username">ID number</label><input id="username" name="username" inputmode="numeric" pattern="[0-9]{5,9}" maxlength="9" autocomplete="off" required><label for="phone">Mobile number</label><input id="phone" name="mobilePhoneNumber" type="tel" pattern="05[0-9]{8}" maxlength="10" autocomplete="off" required>';submit.textContent='Send SMS code'}else if(step==='otp'){document.getElementById('title').textContent='Check your phone';document.getElementById('intro').textContent='Enter the code sent by Meuhedet.';fields.innerHTML='<label for="code">SMS code</label><input id="code" name="code" inputmode="numeric" pattern="[0-9]{4,8}" maxlength="8" autocomplete="one-time-code" required>';submit.textContent='Connect account';document.getElementById('code').focus()}else{fields.replaceChildren();document.getElementById('title').textContent=step==='complete'?'Your account is connected':step==='working'?'Connecting your account':'Sign-in ended';document.getElementById('intro').textContent=step==='complete'?'Your agent can now retrieve your records.':step==='working'?'Please wait for sign-in to finish.':'Ask your agent to open a new sign-in form.'}}
window.addEventListener('message',event=>{if(event.source!==window.parent||event.data?.jsonrpc!=='2.0')return;const data=event.data;if(pending.has(data.id)){const item=pending.get(data.id);pending.delete(data.id);clearTimeout(item.timer);data.error?item.reject(Error('The local sign-in action failed.')):item.resolve(data.result)}else if(data.method==='ui/notifications/tool-result'){render(data.params)}});
async function action(name,data={}){if(!flowId)throw Error('Ask your agent to open a new sign-in form.');return request('tools/call',{name:'meuhedet_sign_in_action',arguments:{flowId,action:name,...data}})}
form.addEventListener('submit',async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(form));form.reset();submit.disabled=true;cancel.disabled=true;forget.disabled=true;message.textContent=step==='credentials'?'Requesting your SMS code…':'Connecting your account…';try{render(await action(step==='credentials'&&hasSavedDetails?'saved':step,data))}catch(error){fields.replaceChildren();form.hidden=true;message.textContent=error.message}finally{submit.disabled=false;cancel.disabled=false;forget.disabled=false}});
cancel.addEventListener('click',async()=>{try{render(await action('cancel'))}catch(error){fields.replaceChildren();form.hidden=true;message.textContent=error.message}});
forget.addEventListener('click',async()=>{forget.disabled=true;try{render(await action('forget'))}catch(error){message.textContent=error.message}finally{forget.disabled=false}});
request('ui/initialize',{appInfo:{name:'meuhedet-sign-in',version:'0.1.0'},appCapabilities:{},protocolVersion:'2026-01-26'}).then(()=>{window.parent.postMessage({jsonrpc:'2.0',method:'ui/notifications/initialized'},'*')}).catch(error=>{message.textContent=error.message});
</script>`;
